package xd.harm.utils.render;

import com.mojang.blaze3d.matrix.MatrixStack;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.BufferBuilder;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.client.renderer.vertex.DefaultVertexFormats;
import net.minecraft.util.math.AxisAlignedBB;
import org.lwjgl.opengl.GL11;
import xd.harm.events.render.EventRender3D;

public class Render3D {

    public static void setup3dForBlockPos(EventRender3D event, Runnable render, boolean bloom, boolean disableDepth) {
        event.getStack().push();
        event.getStack().translate(-Minecraft.getInstance().getRenderManager().renderPosX(), -Minecraft.getInstance().getRenderManager().renderPosY(), -Minecraft.getInstance().getRenderManager().renderPosZ());
        GL11.glBlendFunc(GL11.GL_SRC_ALPHA, bloom ? GL11.GL_ONE : GL11.GL_ONE_MINUS_SRC_ALPHA);
        GL11.glEnable(GL11.GL_BLEND);
        GL11.glLineWidth(1.0f);
        GL11.glDisable(GL11.GL_TEXTURE_2D);
        if (disableDepth) GL11.glDepthMask(false);
        else GL11.glDepthMask(true);
        GL11.glDisable(GL11.GL_LIGHTING);
        GL11.glShadeModel(GL11.GL_SMOOTH);
        render.run();
        GL11.glLineWidth(1.0f);
        GL11.glShadeModel(GL11.GL_FLAT);
        GL11.glEnable(GL11.GL_TEXTURE_2D);
        if (disableDepth) GL11.glDepthMask(true);
        GL11.glDisable(GL11.GL_BLEND);
        event.getStack().pop();
    }

    public static void drawCanisterBox(MatrixStack matrixIn, BufferBuilder buffer, Tessellator tessellator, AxisAlignedBB aabb, boolean outlineBox, boolean decussationBox, boolean fullBox, int outlineColor, int decussationColor, int fullColor) {
        GL11.glDisable(GL11.GL_ALPHA_TEST);
        GL11.glEnable(GL11.GL_LINE_SMOOTH);
        GL11.glHint(GL11.GL_LINE_SMOOTH_HINT, GL11.GL_NICEST);
        if (outlineBox) {
            buffer.begin(2, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(outlineColor).endVertex();
            tessellator.draw();
            buffer.begin(2, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(outlineColor).endVertex();
            tessellator.draw();
            buffer.begin(2, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(outlineColor).endVertex();
            tessellator.draw();
            buffer.begin(2, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(outlineColor).endVertex();
            tessellator.draw();
            buffer.begin(2, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(outlineColor).endVertex();
            tessellator.draw();
            buffer.begin(2, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(outlineColor).endVertex();
            tessellator.draw();
        }
        if (decussationBox) {
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(decussationColor).endVertex();
            tessellator.draw();
            buffer.begin(1, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(decussationColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(decussationColor).endVertex();
            tessellator.draw();
        }
        if (fullBox) {
            buffer.begin(7, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.maxY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.minX, (float) aabb.minY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.minZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.maxY, (float) aabb.maxZ).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), (float) aabb.maxX, (float) aabb.minY, (float) aabb.maxZ).color(fullColor).endVertex();
            tessellator.draw();
        }
        GL11.glEnable(GL11.GL_ALPHA_TEST);
        GL11.glHint(GL11.GL_LINE_SMOOTH_HINT, GL11.GL_DONT_CARE);
        GL11.glDisable(GL11.GL_LINE_SMOOTH);
        GL11.glLineWidth(1.F);
    }

    public static void drawGradientAlphaBox(MatrixStack matrixIn, BufferBuilder buffer, Tessellator tessellator, AxisAlignedBB aabb, boolean outlineBox, boolean fullBox, int outlineColor, int fullColor) {
        GL11.glDisable(GL11.GL_ALPHA_TEST);
        GL11.glDisable(GL11.GL_CULL_FACE);
        GL11.glShadeModel(GL11.GL_SMOOTH);
        GL11.glEnable(GL11.GL_LINE_SMOOTH);
        float x1 = (float) aabb.minX;
        float y1 = (float) aabb.minY;
        float z1 = (float) aabb.minZ;
        float x2 = (float) aabb.maxX;
        float y2 = (float) aabb.maxY;
        float z2 = (float) aabb.maxZ;
        float wx = x2 - x1;
        float wz = z2 - z1;
        if (outlineBox) {
            buffer.begin(GL11.GL_LINE_LOOP, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z2).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z2).color(outlineColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_LINE_STRIP, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y2, z1).color(0).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_LINE_STRIP, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y2, z1).color(0).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_LINE_STRIP, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z2).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y2, z2).color(0).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_LINE_STRIP, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z2).color(outlineColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y2, z2).color(0).endVertex();
            tessellator.draw();
        }
        if (fullBox) {
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z1 + wz / 2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1 + wz / 2).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z1 + wz / 2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1 + wz / 2).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z2).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z2).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z1 + wz / 2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1 + wz / 2).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z2).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z2).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1 + wx / 2, y1, z1 + wz / 2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1 + wz / 2).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y2, z1).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y2, z1).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y2, z1).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y2, z2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z2).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y1, z2).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x1, y2, z2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y2, z2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z2).color(fullColor).endVertex();
            tessellator.draw();
            buffer.begin(GL11.GL_QUADS, DefaultVertexFormats.POSITION_COLOR);
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z1).color(fullColor).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y2, z1).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y2, z2).color(0).endVertex();
            buffer.pos(matrixIn.getLast().getMatrix(), x2, y1, z2).color(fullColor).endVertex();
            tessellator.draw();
        }
        GL11.glDisable(GL11.GL_LINE_SMOOTH);
        GL11.glShadeModel(GL11.GL_FLAT);
        GL11.glEnable(GL11.GL_ALPHA_TEST);
        GL11.glEnable(GL11.GL_CULL_FACE);
        GL11.glLineWidth(1.F);
    }
}
